import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./navbar/navbar";
import { StoreProvider } from "@/store/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
